/**
 * Sprite atlas access. The atlas (PNG + JSON index) is generated by
 * scripts/generate-sprites.mjs from the shared asset catalog. The desktop
 * app passes URLs; this module loads and indexes them.
 */

export interface SpriteRect {
  x: number;
  y: number;
  w: number;
  h: number;
  kind: "floor" | "wall" | "object" | "character";
  frames?: number;
  frameW?: number;
  frameH?: number;
  wTiles?: number;
  hTiles?: number;
}

export interface SpriteAtlas {
  tileSize: number;
  image: HTMLImageElement;
  sprites: Record<string, SpriteRect>;
}

export async function loadAtlas(pngUrl: string, jsonUrl: string): Promise<SpriteAtlas> {
  const [indexResponse, image] = await Promise.all([fetch(jsonUrl), loadImage(pngUrl)]);
  if (!indexResponse.ok) {
    throw new Error(`Failed to load atlas index: ${String(indexResponse.status)}`);
  }
  const index = (await indexResponse.json()) as {
    tileSize: number;
    sprites: Record<string, SpriteRect>;
  };
  return { tileSize: index.tileSize, image, sprites: index.sprites };
}

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => { resolve(img); };
    img.onerror = () => { reject(new Error(`Failed to load atlas image: ${url}`)); };
    img.src = url;
  });
}

/** Walk-strip frame index for a facing + animation step. */
export function characterFrame(
  facing: "down" | "up" | "left" | "right",
  step: 0 | 1 | 2,
): number {
  const dirIndex = { down: 0, up: 1, left: 2, right: 3 }[facing];
  return dirIndex * 3 + step;
}
